-- ================================================================
-- HOUSING INTELLIGENCE DATABASE SETUP
-- ================================================================
-- This script creates the database structure for housing sales analysis
-- with Snowflake Cortex Analyst capabilities

-- Create database and schema
CREATE OR REPLACE DATABASE HOUSING_INTELLIGENCE;
CREATE OR REPLACE SCHEMA HOUSING_INTELLIGENCE.CORE;

USE DATABASE HOUSING_INTELLIGENCE;
USE SCHEMA CORE;

-- ================================================================
-- CUSTOMERS TABLE
-- ================================================================
CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100),
    PHONE VARCHAR(20),
    DATE_OF_BIRTH DATE,
    ANNUAL_INCOME NUMBER(12,2),
    CREDIT_SCORE NUMBER(3,0),
    EMPLOYMENT_STATUS VARCHAR(50),
    MARITAL_STATUS VARCHAR(20),
    FAMILY_SIZE NUMBER(2,0),
    PREFERRED_LOCATION VARCHAR(100),
    BUDGET_MIN NUMBER(12,2),
    BUDGET_MAX NUMBER(12,2),
    CUSTOMER_SINCE DATE,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

-- ================================================================
-- HOUSE_CHARACTERISTICS TABLE
-- ================================================================
CREATE OR REPLACE TABLE HOUSE_CHARACTERISTICS (
    HOUSE_ID NUMBER(10,0) NOT NULL,
    ADDRESS VARCHAR(200) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIP_CODE VARCHAR(10) NOT NULL,
    BEDROOMS NUMBER(2,0),
    BATHROOMS NUMBER(3,1),
    SQUARE_FOOTAGE NUMBER(6,0),
    LOT_SIZE_SQFT NUMBER(8,0),
    YEAR_BUILT NUMBER(4,0),
    PROPERTY_TYPE VARCHAR(50),
    GARAGE_SPACES NUMBER(1,0),
    HAS_POOL BOOLEAN,
    HAS_FIREPLACE BOOLEAN,
    HAS_BASEMENT BOOLEAN,
    FLOORING_TYPE VARCHAR(50),
    HEATING_TYPE VARCHAR(50),
    COOLING_TYPE VARCHAR(50),
    NEIGHBORHOOD VARCHAR(100),
    SCHOOL_DISTRICT VARCHAR(100),
    WALK_SCORE NUMBER(3,0),
    CRIME_RATE VARCHAR(20),
    LISTING_DATE DATE,
    LISTING_PRICE NUMBER(12,2),
    PROPERTY_TAX_ANNUAL NUMBER(8,2),
    HOA_FEE_MONTHLY NUMBER(6,2),
    CONSTRAINT PK_HOUSE_CHARACTERISTICS PRIMARY KEY (HOUSE_ID)
);

-- ================================================================
-- HOUSE_SALES TABLE
-- ================================================================
CREATE OR REPLACE TABLE HOUSE_SALES (
    SALE_ID NUMBER(10,0) NOT NULL,
    HOUSE_ID NUMBER(10,0) NOT NULL,
    CUSTOMER_ID NUMBER(10,0) NOT NULL,
    SALE_DATE DATE NOT NULL,
    SALE_PRICE NUMBER(12,2) NOT NULL,
    LISTING_PRICE NUMBER(12,2),
    DAYS_ON_MARKET NUMBER(4,0),
    SALE_TYPE VARCHAR(50), -- 'Cash', 'Financed', 'FHA', 'VA', etc.
    AGENT_ID NUMBER(8,0),
    AGENT_NAME VARCHAR(100),
    COMMISSION_RATE NUMBER(4,3),
    COMMISSION_AMOUNT NUMBER(10,2),
    FINANCING_TYPE VARCHAR(50),
    DOWN_PAYMENT_AMOUNT NUMBER(12,2),
    LOAN_AMOUNT NUMBER(12,2),
    INTEREST_RATE NUMBER(5,3),
    CLOSING_COSTS NUMBER(8,2),
    INSPECTION_PASSED BOOLEAN,
    APPRAISAL_VALUE NUMBER(12,2),
    CONTINGENCIES VARCHAR(500),
    SALE_STATUS VARCHAR(20) DEFAULT 'COMPLETED',
    CONSTRAINT PK_HOUSE_SALES PRIMARY KEY (SALE_ID),
    CONSTRAINT FK_SALES_HOUSE FOREIGN KEY (HOUSE_ID) REFERENCES HOUSE_CHARACTERISTICS(HOUSE_ID),
    CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- ================================================================
-- CREATE INDEXES FOR PERFORMANCE
-- ================================================================
CREATE INDEX IDX_CUSTOMERS_INCOME ON CUSTOMERS(ANNUAL_INCOME);
CREATE INDEX IDX_CUSTOMERS_CREDIT ON CUSTOMERS(CREDIT_SCORE);
CREATE INDEX IDX_HOUSE_LOCATION ON HOUSE_CHARACTERISTICS(CITY, STATE);
CREATE INDEX IDX_HOUSE_PRICE ON HOUSE_CHARACTERISTICS(LISTING_PRICE);
CREATE INDEX IDX_HOUSE_SIZE ON HOUSE_CHARACTERISTICS(SQUARE_FOOTAGE);
CREATE INDEX IDX_SALES_DATE ON HOUSE_SALES(SALE_DATE);
CREATE INDEX IDX_SALES_PRICE ON HOUSE_SALES(SALE_PRICE);

-- ================================================================
-- GRANT PERMISSIONS (Assuming SYSADMIN role)
-- ================================================================
GRANT ALL ON DATABASE HOUSING_INTELLIGENCE TO ROLE SYSADMIN;
GRANT ALL ON SCHEMA HOUSING_INTELLIGENCE.CORE TO ROLE SYSADMIN;
GRANT ALL ON ALL TABLES IN SCHEMA HOUSING_INTELLIGENCE.CORE TO ROLE SYSADMIN;

COMMENT ON DATABASE HOUSING_INTELLIGENCE IS 'Database for housing sales analysis with Cortex Analyst capabilities';
COMMENT ON SCHEMA HOUSING_INTELLIGENCE.CORE IS 'Core schema containing house sales, characteristics, and customer data';
COMMENT ON TABLE CUSTOMERS IS 'Customer information including demographics and preferences';
COMMENT ON TABLE HOUSE_CHARACTERISTICS IS 'Detailed characteristics and features of houses available for sale';
COMMENT ON TABLE HOUSE_SALES IS 'Transaction records of completed house sales';