-- Purchase Agreement Registration SQL
-- Generated by purchase_agreements_generator_updated.py
-- Uses ACTUAL sales data from 03_house_sales_2022_2023.sql

USE DATABASE HOUSING_INTELLIGENCE;
USE SCHEMA CORE;

-- Register all purchase agreement PDFs with actual sales data

CALL REGISTER_PURCHASE_AGREEMENT(
    3001,
    'agreement_3001.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3001.pdf',
    '2022-02-13',
    '2022-03-15',
    'Inspection contingency | Financing: Conventional | Down Payment: $75,000.00 | Loan: $300,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3002,
    'agreement_3002.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3002.pdf',
    '2022-02-18',
    '2022-03-20',
    'Financing contingency | Financing: FHA | Down Payment: $14,000.00 | Loan: $266,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3003,
    'agreement_3003.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3003.pdf',
    '2022-03-02',
    '2022-04-01',
    'Appraisal contingency | Financing: Conventional | Down Payment: $95,000.00 | Loan: $380,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3004,
    'agreement_3004.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3004.pdf',
    '2022-03-11',
    '2022-04-10',
    'VA inspection | Financing: VA | Down Payment: $0.00 | Loan: $315,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3005,
    'agreement_3005.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3005.pdf',
    '2022-03-16',
    '2022-04-15',
    'Standard terms and conditions apply | Financing: Cash | Cash Purchase: $615,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3006,
    'agreement_3006.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3006.pdf',
    '2022-03-26',
    '2022-04-25',
    'Inspection contingency | Financing: FHA | Down Payment: $11,250.00 | Loan: $213,750.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3007,
    'agreement_3007.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3007.pdf',
    '2022-04-05',
    '2022-05-05',
    'Appraisal contingency | Financing: Conventional | Down Payment: $85,000.00 | Loan: $340,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3008,
    'agreement_3008.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3008.pdf',
    '2022-04-12',
    '2022-05-12',
    'Standard terms and conditions apply | Financing: Conventional | Down Payment: $58,000.00 | Loan: $232,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3009,
    'agreement_3009.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3009.pdf',
    '2022-04-20',
    '2022-05-20',
    'Inspection contingency | Financing: Conventional | Down Payment: $107,000.00 | Loan: $428,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3010,
    'agreement_3010.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3010.pdf',
    '2022-04-28',
    '2022-05-28',
    'Appraisal contingency | Financing: Conventional | Down Payment: $81,000.00 | Loan: $324,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3011,
    'agreement_3011.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3011.pdf',
    '2022-05-16',
    '2022-06-15',
    'Appraisal contingency | Financing: Conventional | Down Payment: $133,000.00 | Loan: $532,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3012,
    'agreement_3012.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3012.pdf',
    '2022-05-23',
    '2022-06-22',
    'Tech company relocation | Financing: Conventional | Down Payment: $179,000.00 | Loan: $716,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3013,
    'agreement_3013.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3013.pdf',
    '2022-06-10',
    '2022-07-10',
    'Luxury home inspection | Financing: Jumbo | Down Payment: $245,000.00 | Loan: $980,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3014,
    'agreement_3014.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3014.pdf',
    '2022-06-18',
    '2022-07-18',
    'Earthquake contingency | Financing: Conventional | Down Payment: $153,000.00 | Loan: $612,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3015,
    'agreement_3015.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3015.pdf',
    '2022-06-25',
    '2022-07-25',
    'Financing contingency | Financing: Conventional | Down Payment: $93,000.00 | Loan: $372,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3016,
    'agreement_3016.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3016.pdf',
    '2022-07-06',
    '2022-08-05',
    'Hurricane insurance | Financing: Conventional | Down Payment: $91,000.00 | Loan: $364,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3017,
    'agreement_3017.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3017.pdf',
    '2022-07-13',
    '2022-08-12',
    'Golf membership transfer | Financing: Conventional | Down Payment: $75,000.00 | Loan: $300,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3018,
    'agreement_3018.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3018.pdf',
    '2022-07-21',
    '2022-08-20',
    'Beachfront assessment | Financing: FHA | Down Payment: $15,750.00 | Loan: $299,250.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3019,
    'agreement_3019.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3019.pdf',
    '2022-07-29',
    '2022-08-28',
    'Theme park proximity | Financing: Conventional | Down Payment: $85,000.00 | Loan: $340,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3020,
    'agreement_3020.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3020.pdf',
    '2022-08-06',
    '2022-09-05',
    'River access rights | Financing: Conventional | Down Payment: $57,000.00 | Loan: $228,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3021,
    'agreement_3021.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3021.pdf',
    '2022-09-15',
    '2022-10-15',
    'Mountain view preservation | Financing: Conventional | Down Payment: $101,000.00 | Loan: $404,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3022,
    'agreement_3022.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3022.pdf',
    '2022-09-22',
    '2022-10-22',
    'Ski area access | Financing: Conventional | Down Payment: $131,000.00 | Loan: $524,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3023,
    'agreement_3023.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3023.pdf',
    '2022-10-11',
    '2022-11-10',
    'Urban loft conversion | Financing: Cash | Cash Purchase: $415,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3024,
    'agreement_3024.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3024.pdf',
    '2022-10-19',
    '2022-11-18',
    'Military base proximity | Financing: Conventional | Down Payment: $71,000.00 | Loan: $284,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3025,
    'agreement_3025.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3025.pdf',
    '2022-10-26',
    '2022-11-25',
    'VA benefits transfer | Financing: VA | Down Payment: $0.00 | Loan: $375,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3026,
    'agreement_3026.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3026.pdf',
    '2022-11-05',
    '2022-12-05',
    'Desert landscaping | Financing: Conventional | Down Payment: $75,000.00 | Loan: $300,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3027,
    'agreement_3027.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3027.pdf',
    '2022-11-12',
    '2022-12-12',
    'Golf course access | Financing: Conventional | Down Payment: $131,000.00 | Loan: $524,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3028,
    'agreement_3028.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3028.pdf',
    '2022-11-20',
    '2022-12-20',
    'University district | Financing: FHA | Down Payment: $13,750.00 | Loan: $261,250.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3029,
    'agreement_3029.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3029.pdf',
    '2022-11-28',
    '2022-12-28',
    'Retirement community | Financing: Conventional | Down Payment: $83,000.00 | Loan: $332,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3030,
    'agreement_3030.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3030.pdf',
    '2022-12-16',
    '2023-01-15',
    'Desert climate adaptation | Financing: Conventional | Down Payment: $57,000.00 | Loan: $228,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3031,
    'agreement_3031.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3031.pdf',
    '2023-01-11',
    '2023-02-10',
    'Mountain cabin features | Financing: Cash | Cash Purchase: $475,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3032,
    'agreement_3032.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3032.pdf',
    '2023-01-19',
    '2023-02-18',
    'Wine cellar inspection | Financing: Jumbo | Down Payment: $219,000.00 | Loan: $876,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3033,
    'agreement_3033.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3033.pdf',
    '2023-02-03',
    '2023-03-05',
    'Lakefront rights | Financing: Jumbo | Down Payment: $359,000.00 | Loan: $1,436,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3034,
    'agreement_3034.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3034.pdf',
    '2023-02-13',
    '2023-03-15',
    'Tech headquarters relocation | Financing: Jumbo | Down Payment: $285,000.00 | Loan: $1,140,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3035,
    'agreement_3035.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3035.pdf',
    '2023-02-20',
    '2023-03-22',
    'Marina access rights | Financing: Jumbo | Down Payment: $219,000.00 | Loan: $876,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3036,
    'agreement_3036.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3036.pdf',
    '2023-03-06',
    '2023-04-05',
    'Celebrity privacy clause | Financing: Jumbo | Down Payment: $559,000.00 | Loan: $2,236,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3037,
    'agreement_3037.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3037.pdf',
    '2023-03-13',
    '2023-04-12',
    'Historic district compliance | Financing: Jumbo | Down Payment: $329,000.00 | Loan: $1,316,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3038,
    'agreement_3038.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3038.pdf',
    '2023-03-21',
    '2023-04-20',
    'Entertainment district location | Financing: Conventional | Down Payment: $175,000.00 | Loan: $700,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3039,
    'agreement_3039.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3039.pdf',
    '2023-03-29',
    '2023-04-28',
    'Oceanfront hurricane insurance | Financing: Conventional | Down Payment: $171,000.00 | Loan: $684,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3040,
    'agreement_3040.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3040.pdf',
    '2023-04-15',
    '2023-05-15',
    'River Oaks historic preservation | Financing: Jumbo | Down Payment: $359,000.00 | Loan: $1,436,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3041,
    'agreement_3041.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3041.pdf',
    '2023-04-22',
    '2023-05-22',
    'Memorial Villages exclusivity | Financing: Conventional | Down Payment: $179,000.00 | Loan: $716,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3042,
    'agreement_3042.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3042.pdf',
    '2023-05-06',
    '2023-06-05',
    'Galleria shopping access | Financing: Conventional | Down Payment: $93,000.00 | Loan: $372,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3043,
    'agreement_3043.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3043.pdf',
    '2023-06-12',
    '2023-07-12',
    'Art Deco historic value | Financing: Conventional | Down Payment: $133,000.00 | Loan: $532,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3044,
    'agreement_3044.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3044.pdf',
    '2023-06-20',
    '2023-07-20',
    'Coral Gables architectural review | Financing: Jumbo | Down Payment: $219,000.00 | Loan: $876,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3045,
    'agreement_3045.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3045.pdf',
    '2023-07-06',
    '2023-08-05',
    'Beach access rights | Financing: Conventional | Down Payment: $83,000.00 | Loan: $332,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3046,
    'agreement_3046.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3046.pdf',
    '2023-07-16',
    '2023-08-15',
    'Ski-in ski-out privileges | Financing: Cash | Cash Purchase: $2,175,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3047,
    'agreement_3047.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3047.pdf',
    '2023-07-23',
    '2023-08-22',
    'Ski resort amenities | Financing: Jumbo | Down Payment: $185,000.00 | Loan: $740,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3048,
    'agreement_3048.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3048.pdf',
    '2023-08-11',
    '2023-09-10',
    'Cherry Creek luxury shopping | Financing: Conventional | Down Payment: $133,000.00 | Loan: $532,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3049,
    'agreement_3049.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3049.pdf',
    '2023-08-19',
    '2023-09-18',
    'Family community amenities | Financing: Conventional | Down Payment: $121,000.00 | Loan: $484,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3050,
    'agreement_3050.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3050.pdf',
    '2023-09-05',
    '2023-10-05',
    'Desert mountain privacy | Financing: Jumbo | Down Payment: $285,000.00 | Loan: $1,140,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3051,
    'agreement_3051.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3051.pdf',
    '2023-09-15',
    '2023-10-15',
    'Camelback mountain views | Financing: Conventional | Down Payment: $93,000.00 | Loan: $372,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3052,
    'agreement_3052.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3052.pdf',
    '2023-09-22',
    '2023-10-22',
    'Red rock hiking access | Financing: Conventional | Down Payment: $121,000.00 | Loan: $484,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3053,
    'agreement_3053.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3053.pdf',
    '2023-10-06',
    '2023-11-05',
    'Biltmore district exclusivity | Financing: Conventional | Down Payment: $141,000.00 | Loan: $564,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3054,
    'agreement_3054.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3054.pdf',
    '2023-10-16',
    '2023-11-15',
    'Bay Area tech transfer | Financing: Conventional | Down Payment: $121,000.00 | Loan: $484,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3055,
    'agreement_3055.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3055.pdf',
    '2023-10-23',
    '2023-11-22',
    'Coastal commission approval | Financing: Jumbo | Down Payment: $219,000.00 | Loan: $876,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3056,
    'agreement_3056.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3056.pdf',
    '2023-11-05',
    '2023-12-05',
    'Stanford University proximity | Financing: Jumbo | Down Payment: $175,000.00 | Loan: $700,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3057,
    'agreement_3057.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3057.pdf',
    '2023-11-15',
    '2023-12-15',
    'Investment property | Financing: Conventional | Down Payment: $61,000.00 | Loan: $244,000.00'
);

CALL REGISTER_PURCHASE_AGREEMENT(
    3058,
    'agreement_3058.pdf',
    '@PURCHASE_AGREEMENTS_STAGE/agreement_3058.pdf',
    '2023-11-22',
    '2023-12-22',
    'End of year closing | Financing: Conventional | Down Payment: $77,000.00 | Loan: $308,000.00'
);
